# Generated by Django 5.1.3 on 2025-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='user_name')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
